FROM node:trixie-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install --no-install-recommends -y libreoffice python3-uno python3-pip && \
    pip3 install --break-system-packages unoserver && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

EXPOSE 2003

CMD ["unoserver", "--interface", "0.0.0.0", "--port", "2003"]
