services:
  viesdoknuskaitytojas:
    # build: .
    image: ghcr.io/viespirkiu-grupe/doknuskaitytojas:latest
    container_name: viesdoknuskaitytojas
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
